framework:
    rate_limiter:
        authenticated_request:
            policy: 'token_bucket'
            limit: 5000
            rate: { interval: '15 minutes', amount: 500 }
            lock_factory: null